import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KickCraft",
  description: "Generated by create next app",

  openGraph: {
    title: "KickCraft",
    description: "Premium sneaker store",
    images: [
      {
        url: "/og-banner.webp", // path from /public
        width: 1200,
        height: 630,
        alt: "KickCraft – Premium Sneakers",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "KickCraft",
    description: "Premium sneaker store",
    images: ["/og-banner.webp"],
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
